#!/usr/bin/env bash

./stop || true
./build docker || exit 1

echo "### Starting lobby service docker ###"

lobby_service_port=${LOBBY_SERVICE_PORT:-8080}
docker run --rm --name lobby-service -d -e JAVA_MAX_HEAP_SIZE=2G -e LOBBY_DB_URL=${LOBBY_DB_URL} -p ${lobby_service_port}:8080 docker-io.dbc.dk/lobby-service:devel

attempts=0
max_attempts=60
until $(curl --output /dev/null --silent --head --fail http://localhost:${lobby_service_port}/status); do
    if [[ ${attempts} -eq ${max_attempts} ]]; then
        break
    fi

    printf '.'
    attempts=$(($attempts+1))
    sleep 0.5
done

echo ""
echo "### Status for lobby service ###"
curl -vs http://localhost:${lobby_service_port}/status
echo ""
