#!/usr/bin/env bash

case "$1" in
    docker)
        echo "### building lobby service docker ###"
        docker build -f target/docker/Dockerfile --pull --no-cache . -t docker-metascrum.artifacts.dbccloud.dk/lobby-service:devel || exit 1
        if [[ ! -z "$BUILD_NUMBER" ]]; then
            docker tag docker-metascrum.artifacts.dbccloud.dk/lobby-service:devel docker-metascrum.artifacts.dbccloud.dk/lobby-service:${BRANCH_NAME}-${BUILD_NUMBER}
        fi
        ;;

    *)
        echo "### building lobby project ###"
        echo "### Look for build artifacts in target/ ###"

        mvn package -Dmaven.test.skip=true || exit 1
        ;;
esac

